# Usa la imagen base de Node.js
FROM node:20-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Instalar dependencias
RUN yarn install

# Exponer el puerto del frontend
EXPOSE 5173

# Comando por defecto para iniciar el servidor de desarrollo
CMD ["yarn", "dev"]
