services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: imesero-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - imesero-network
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        composer install --no-interaction
        php artisan migrate --force
        php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: imesero-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - imesero-network

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: imesero
      POSTGRES_USER: imesero_user
      POSTGRES_PASSWORD: imeseropass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - imesero-network

networks:
  imesero-network:

volumes:
  db_data:
