<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Categoria;
use App\Models\Producto;

class ProductoSeeder extends Seeder
{
    public function run()
    {
        $productos = [
            // Primeros
            [
                'nombre_es' => 'Ensalada de queso de cabra y frutos secos',
                'nombre_ca' => 'Amanida de formatge de cabra i fruits secs',
                'nombre_en' => 'Goat cheese and nuts salad',
                'descripcion_es' => 'Ensalada fresca con queso de cabra, nueces y vinagreta especial.',
                'descripcion_ca' => 'Amanida fresca amb formatge de cabra, nous i vinagreta especial.',
                'descripcion_en' => 'Fresh salad with goat cheese, walnuts, and special vinaigrette.',
                'ingredientes_es' => 'Queso de cabra, nueces, lechuga, vinagreta',
                'ingredientes_ca' => 'Formatge de cabra, nous, enciam, vinagreta',
                'ingredientes_en' => 'Goat cheese, walnuts, lettuce, vinaigrette',
                'precio' => 12.00,
                'categoria' => 'Primeros',
                'imagen' => '/Imagenes/Menu/ensalada-de-queso-de-cabra-y-frutos-secos.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Salmón marinado con salsa tártara',
                'nombre_ca' => 'Salmó marinat amb salsa tàrtara',
                'nombre_en' => 'Marinated salmon with tartar sauce',
                'descripcion_es' => 'Salmón fresco marinado acompañado de salsa tártara casera.',
                'descripcion_ca' => 'Salmó fresc marinat amb salsa tàrtara casolana.',
                'descripcion_en' => 'Fresh marinated salmon with homemade tartar sauce.',
                'ingredientes_es' => 'Salmón, salsa tártara, eneldo, limón',
                'ingredientes_ca' => 'Salmó, salsa tàrtara, anet, llimona',
                'ingredientes_en' => 'Salmon, tartar sauce, dill, lemon',
                'precio' => 14.00,
                'categoria' => 'Primeros',
                'imagen' => '/Imagenes/Menu/salmon-marinado.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Canelones rustidos',
                'nombre_ca' => 'Canelons rostits',
                'nombre_en' => 'Roasted meat cannelloni',
                'descripcion_es' => 'Canelones caseros rellenos de carne rustida al horno.',
                'descripcion_ca' => 'Canelons casolans farcits de carn rostida al forn.',
                'descripcion_en' => 'Homemade cannelloni filled with oven-roasted meat.',
                'ingredientes_es' => 'Carne rustida, pasta de canelón, bechamel',
                'ingredientes_ca' => 'Carn rostida, pasta de caneló, beixamel',
                'ingredientes_en' => 'Roasted meat, cannelloni pasta, béchamel sauce',
                'precio' => 13.00,
                'categoria' => 'Primeros',
                'imagen' => '/Imagenes/Menu/canelones.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Mejillones a la vinagreta',
                'nombre_ca' => 'Musclos a la vinagreta',
                'nombre_en' => 'Mussels with vinaigrette',
                'descripcion_es' => 'Mejillones frescos aliñados con vinagreta de verduras.',
                'descripcion_ca' => 'Musclos frescos amanits amb vinagreta de verdures.',
                'descripcion_en' => 'Fresh mussels seasoned with vegetable vinaigrette.',
                'ingredientes_es' => 'Mejillones, cebolla, pimiento, vinagre',
                'ingredientes_ca' => 'Musclos, ceba, pebrot, vinagre',
                'ingredientes_en' => 'Mussels, onion, bell pepper, vinegar',
                'precio' => 11.00,
                'categoria' => 'Primeros',
                'imagen' => '/Imagenes/Menu/mejillones-a-la-vinagreta.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Cigalas salteadas',
                'nombre_ca' => 'Escamarlans saltats',
                'nombre_en' => 'Sautéed Norway lobsters',
                'descripcion_es' => 'Cigalas salteadas al ajillo con un toque de limón.',
                'descripcion_ca' => 'Escamarlans saltats amb all i un toc de llimona.',
                'descripcion_en' => 'Sautéed Norway lobsters with garlic and a hint of lemon.',
                'ingredientes_es' => 'Cigalas, ajo, perejil, limón',
                'ingredientes_ca' => 'Escamarlans, all, julivert, llimona',
                'ingredientes_en' => 'Norway lobsters, garlic, parsley, lemon',
                'precio' => 16.00,
                'categoria' => 'Primeros',
                'imagen' => '/Imagenes/Menu/cigalas-salteadas.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Chipirones fritos',
                'nombre_ca' => 'Calamarsets fregits',
                'nombre_en' => 'Fried baby squids',
                'descripcion_es' => 'Chipirones fritos crujientes acompañados de alioli.',
                'descripcion_ca' => 'Calamarsets fregits cruixents acompanyats d’allioli.',
                'descripcion_en' => 'Crispy fried baby squids served with aioli.',
                'ingredientes_es' => 'Chipirones, harina, aceite, alioli',
                'ingredientes_ca' => 'Calamarsets, farina, oli, allioli',
                'ingredientes_en' => 'Baby squids, flour, oil, aioli',
                'precio' => 12.00,
                'categoria' => 'Primeros',
                'imagen' => '/Imagenes/Menu/chipirones.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Ensaladilla rusa con bonito',
                'nombre_ca' => 'Amanida russa amb tonyina',
                'nombre_en' => 'Russian salad with tuna',
                'descripcion_es' => 'Ensaladilla clásica con bonito y mayonesa casera.',
                'descripcion_ca' => 'Amanida russa clàssica amb tonyina i maionesa casolana.',
                'descripcion_en' => 'Classic Russian salad with tuna and homemade mayonnaise.',
                'ingredientes_es' => 'Patatas, zanahorias, guisantes, bonito, mayonesa',
                'ingredientes_ca' => 'Patates, pastanagues, pèsols, tonyina, maionesa',
                'ingredientes_en' => 'Potatoes, carrots, peas, tuna, mayonnaise',
                'precio' => 10.00,
                'categoria' => 'Primeros',
                'imagen' => '/Imagenes/Menu/ensaladilla-rusa-bonito.jpg',
                'recomendada' => false,
            ],


            // Segundos
            [
                'nombre_es' => 'Arroz seco de la lonja',
                'nombre_ca' => 'Arròs sec de la llotja',
                'nombre_en' => 'Dry rice with fresh seafood',
                'descripcion_es' => 'Arroz seco con marisco fresco de la lonja.',
                'descripcion_ca' => 'Arròs sec amb marisc fresc de la llotja.',
                'descripcion_en' => 'Dry rice with fresh seafood from the market.',
                'ingredientes_es' => 'Arroz, marisco variado, fumet de pescado',
                'ingredientes_ca' => 'Arròs, marisc variat, fumet de peix',
                'ingredientes_en' => 'Rice, assorted seafood, fish stock',
                'precio' => 18.00,
                'categoria' => 'Segundos',
                'imagen' => '/Imagenes/Menu/arroz-seco-lonja.jpg',
                'recomendada' => true,
            ],
            [
                'nombre_es' => 'Fideuá',
                'nombre_ca' => 'Fideuada',
                'nombre_en' => 'Fideuá (noodle paella)',
                'descripcion_es' => 'Fideuá tradicional con alioli de acompañamiento.',
                'descripcion_ca' => 'Fideuada tradicional amb allioli d’acompanyament.',
                'descripcion_en' => 'Traditional fideuá served with aioli.',
                'ingredientes_es' => 'Fideos, sepia, marisco, fumet',
                'ingredientes_ca' => 'Fideus, sípia, marisc, fumet',
                'ingredientes_en' => 'Noodles, cuttlefish, seafood, fish stock',
                'precio' => 17.00,
                'categoria' => 'Segundos',
                'imagen' => '/Imagenes/Menu/fideua.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Butifarra casera de setas',
                'nombre_ca' => 'Botifarra casolana de bolets',
                'nombre_en' => 'Homemade mushroom sausage',
                'descripcion_es' => 'Butifarra artesana con setas salteadas.',
                'descripcion_ca' => 'Botifarra artesana amb bolets saltats.',
                'descripcion_en' => 'Artisan sausage with sautéed mushrooms.',
                'ingredientes_es' => 'Butifarra, setas variadas, ajo, perejil',
                'ingredientes_ca' => 'Botifarra, bolets variats, all, julivert',
                'ingredientes_en' => 'Sausage, assorted mushrooms, garlic, parsley',
                'precio' => 15.00,
                'categoria' => 'Segundos',
                'imagen' => '/Imagenes/Menu/butifarra.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Timbal de langostino con allioli',
                'nombre_ca' => 'Timbal de llagostí amb allioli',
                'nombre_en' => 'Prawn timbale with aioli',
                'descripcion_es' => 'Timbal de langostino fresco con suave alioli casero.',
                'descripcion_ca' => 'Timbal de llagostí fresc amb suau allioli casolà.',
                'descripcion_en' => 'Fresh prawn timbale with smooth homemade aioli.',
                'ingredientes_es' => 'Langostinos, patata, alioli',
                'ingredientes_ca' => 'Llagostins, patata, allioli',
                'ingredientes_en' => 'Prawns, potato, aioli',
                'precio' => 16.00,
                'categoria' => 'Segundos',
                'imagen' => '/Imagenes/Menu/timball.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Calamar nacional a la plancha',
                'nombre_ca' => 'Calamar nacional a la planxa',
                'nombre_en' => 'Grilled national squid',
                'descripcion_es' => 'Calamar nacional a la plancha con aceite de oliva virgen.',
                'descripcion_ca' => 'Calamar nacional a la planxa amb oli d’oliva verge.',
                'descripcion_en' => 'Grilled national squid with virgin olive oil.',
                'ingredientes_es' => 'Calamar, aceite de oliva, ajo, perejil',
                'ingredientes_ca' => 'Calamar, oli d’oliva, all, julivert',
                'ingredientes_en' => 'Squid, olive oil, garlic, parsley',
                'precio' => 18.00,
                'categoria' => 'Segundos',
                'imagen' => '/Imagenes/Menu/calamar-nacional.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Merluza de palangre a la plancha',
                'nombre_ca' => 'Lluç de palangre a la planxa',
                'nombre_en' => 'Grilled longline hake',
                'descripcion_es' => 'Merluza de palangre cocinada a la plancha con verduras.',
                'descripcion_ca' => 'Lluç de palangre cuinat a la planxa amb verdures.',
                'descripcion_en' => 'Grilled longline hake served with vegetables.',
                'ingredientes_es' => 'Merluza, verduras variadas, aceite de oliva',
                'ingredientes_ca' => 'Lluç, verdures variades, oli d’oliva',
                'ingredientes_en' => 'Hake, assorted vegetables, olive oil',
                'precio' => 20.00,
                'categoria' => 'Segundos',
                'imagen' => '/Imagenes/Menu/merluza-plancha.jpeg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Osobuco al vino del Priorat',
                'nombre_ca' => 'Ossobuco al vi del Priorat',
                'nombre_en' => 'Ossobuco with Priorat wine',
                'descripcion_es' => 'Tierna carne de osobuco cocida lentamente al vino tinto.',
                'descripcion_ca' => 'Tendra carn d’ossobuco cuinada lentament amb vi negre.',
                'descripcion_en' => 'Tender ossobuco meat slowly cooked in red wine.',
                'ingredientes_es' => 'Osobuco, vino tinto Priorat, verduras',
                'ingredientes_ca' => 'Ossobuco, vi negre Priorat, verdures',
                'ingredientes_en' => 'Ossobuco, Priorat red wine, vegetables',
                'precio' => 22.00,
                'categoria' => 'Segundos',
                'imagen' => '/Imagenes/Menu/osobuco.jpg',
                'recomendada' => false,
            ],
            //Bebidas
            [
                'nombre_es' => 'Vino',
                'nombre_ca' => 'Vi',
                'nombre_en' => 'Wine',
                'descripcion_es' => 'Copa de vino tinto o blanco a elección.',
                'descripcion_ca' => 'Copa de vi negre o blanc a elecció.',
                'descripcion_en' => 'Glass of red or white wine of your choice.',
                'ingredientes_es' => 'Uvas seleccionadas',
                'ingredientes_ca' => 'Raïm seleccionat',
                'ingredientes_en' => 'Selected grapes',
                'precio' => 3.00,
                'categoria' => 'Bebidas',
                'imagen' => '/Imagenes/Menu/vino.jpeg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Agua',
                'nombre_ca' => 'Aigua',
                'nombre_en' => 'Water',
                'descripcion_es' => 'Botella de agua mineral natural.',
                'descripcion_ca' => 'Ampolla d’aigua mineral natural.',
                'descripcion_en' => 'Bottle of natural mineral water.',
                'ingredientes_es' => 'Agua mineral',
                'ingredientes_ca' => 'Aigua mineral',
                'ingredientes_en' => 'Mineral water',
                'precio' => 2.00,
                'categoria' => 'Bebidas',
                'imagen' => '/Imagenes/Menu/agua.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Cerveza',
                'nombre_ca' => 'Cervesa',
                'nombre_en' => 'Beer',
                'descripcion_es' => 'Cerveza fría servida en copa.',
                'descripcion_ca' => 'Cervesa freda servida en copa.',
                'descripcion_en' => 'Cold beer served in a glass.',
                'ingredientes_es' => 'Cebada, lúpulo, levadura, agua',
                'ingredientes_ca' => 'Ordi, llúpol, llevat, aigua',
                'ingredientes_en' => 'Barley, hops, yeast, water',
                'precio' => 3.00,
                'categoria' => 'Bebidas',
                'imagen' => '/Imagenes/Menu/cerveza.jpg',
                'recomendada' => true,
            ],

            // Postres
            [
                'nombre_es' => 'Tarta de queso',
                'nombre_ca' => 'Pastís de formatge',
                'nombre_en' => 'Cheesecake',
                'descripcion_es' => 'Tarta de queso cremosa al horno.',
                'descripcion_ca' => 'Pastís de formatge cremós al forn.',
                'descripcion_en' => 'Creamy baked cheesecake.',
                'ingredientes_es' => 'Queso crema, galletas, mantequilla, azúcar',
                'ingredientes_ca' => 'Formatge cremós, galetes, mantega, sucre',
                'ingredientes_en' => 'Cream cheese, biscuits, butter, sugar',
                'precio' => 5.00,
                'categoria' => 'Postres',
                'imagen' => '/Imagenes/Menu/tarta-queso.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Tarta Sacher',
                'nombre_ca' => 'Pastís Sacher',
                'nombre_en' => 'Sacher cake',
                'descripcion_es' => 'Clásica tarta Sacher con cobertura de chocolate.',
                'descripcion_ca' => 'Clàssic pastís Sacher amb cobertura de xocolata.',
                'descripcion_en' => 'Classic Sacher cake with chocolate glaze.',
                'ingredientes_es' => 'Chocolate, harina, azúcar, huevos, mermelada de albaricoque',
                'ingredientes_ca' => 'Xocolata, farina, sucre, ous, melmelada d’albercoc',
                'ingredientes_en' => 'Chocolate, flour, sugar, eggs, apricot jam',
                'precio' => 5.50,
                'categoria' => 'Postres',
                'imagen' => '/Imagenes/Menu/tarta-sacher.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Crema catalana',
                'nombre_ca' => 'Crema catalana',
                'nombre_en' => 'Catalan cream',
                'descripcion_es' => 'Postre tradicional catalán con caramelo quemado.',
                'descripcion_ca' => 'Postre tradicional català amb caramel cremat.',
                'descripcion_en' => 'Traditional Catalan dessert with burnt caramel.',
                'ingredientes_es' => 'Leche, azúcar, huevo, canela, limón',
                'ingredientes_ca' => 'Llet, sucre, ou, canyella, llimona',
                'ingredientes_en' => 'Milk, sugar, egg, cinnamon, lemon',
                'precio' => 4.50,
                'categoria' => 'Postres',
                'imagen' => '/Imagenes/Menu/crema-catalana.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Pudding de la casa con nata',
                'nombre_ca' => 'Púding de la casa amb nata',
                'nombre_en' => 'Homemade pudding with cream',
                'descripcion_es' => 'Pudding casero servido con nata montada.',
                'descripcion_ca' => 'Púding casolà servit amb nata muntada.',
                'descripcion_en' => 'Homemade pudding served with whipped cream.',
                'ingredientes_es' => 'Leche, huevos, azúcar, nata',
                'ingredientes_ca' => 'Llet, ous, sucre, nata',
                'ingredientes_en' => 'Milk, eggs, sugar, cream',
                'precio' => 4.00,
                'categoria' => 'Postres',
                'imagen' => '/Imagenes/Menu/pudding.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Fresas con nata',
                'nombre_ca' => 'Maduixes amb nata',
                'nombre_en' => 'Strawberries with cream',
                'descripcion_es' => 'Fresas frescas con nata montada.',
                'descripcion_ca' => 'Maduixes fresques amb nata muntada.',
                'descripcion_en' => 'Fresh strawberries with whipped cream.',
                'ingredientes_es' => 'Fresas, nata montada',
                'ingredientes_ca' => 'Maduixes, nata muntada',
                'ingredientes_en' => 'Strawberries, whipped cream',
                'precio' => 4.50,
                'categoria' => 'Postres',
                'imagen' => '/Imagenes/Menu/fresas.jpg',
                'recomendada' => false,
            ],
            [
                'nombre_es' => 'Helado de vainilla',
                'nombre_ca' => 'Gelat de vainilla',
                'nombre_en' => 'Vanilla ice cream',
                'descripcion_es' => 'Helado artesanal de vainilla.',
                'descripcion_ca' => 'Gelat artesanal de vainilla.',
                'descripcion_en' => 'Artisan vanilla ice cream.',
                'ingredientes_es' => 'Leche, nata, vainilla, azúcar',
                'ingredientes_ca' => 'Llet, nata, vainilla, sucre',
                'ingredientes_en' => 'Milk, cream, vanilla, sugar',
                'precio' => 4.00,
                'categoria' => 'Postres',
                'imagen' => '/Imagenes/Menu/helado-vainilla.jpg',
                'recomendada' => false,
            ],
        ];

        foreach ($productos as $item) {
            // Crear o encontrar la categoría usando el nombre en español (nombre_es)
            $cat = Categoria::firstOrCreate(
                ['nombre_es' => $item['categoria']],  // Suponemos que 'categoria' es el nombre en español
                ['nombre_es' => $item['categoria']]   // Aseguramos que el nombre de la categoría se asigne a 'nombre_es'
            );

            // Crear o actualizar el producto usando el nombre en español (nombre_es)
            Producto::updateOrCreate(
                ['nombre_es' => $item['nombre_es']],  // Usamos 'nombre_es' como criterio de búsqueda
                [
                    'categoria_id' => $cat->id,
                    'imagen' => $item['imagen'],
                    'nombre_es' => $item['nombre_es'],  // Nombre del producto en español
                    'nombre_ca' => $item['nombre_ca'] ?? null,  // Nombre del producto en catalán, si existe
                    'nombre_en' => $item['nombre_en'] ?? null,  // Nombre del producto en inglés, si existe

                    'descripcion_es' => $item['descripcion_es'], // Descripción en español
                    'descripcion_ca' => $item['descripcion_ca'] ?? null, // Descripción en catalán, si existe
                    'descripcion_en' => $item['descripcion_en'] ?? null, // Descripción en inglés, si existe

                    'ingredientes_es' => $item['ingredientes_es'], // Ingredientes en español
                    'ingredientes_ca' => $item['ingredientes_ca'] ?? null, // Ingredientes en catalán, si existe
                    'ingredientes_en' => $item['ingredientes_en'] ?? null, // Ingredientes en inglés, si existe

                    'precio' => $item['precio'],
                    'disponible' => $item['disponible'] ?? true, // Por defecto, los productos están disponibles
                    'recomendada' => $item['recomendada'] ?? false, // Por defecto, no recomendada
                ]
            );
        }


    }
}
